using System;
using System.IO;
using MHServerEmu.Games.GameData;
using MHServerEmu.Games.GameData.Prototypes;

// One-shot dumper.  Touches GameDatabase.IsInitialized to trigger MHServerEmu's
// static-ctor bootstrap (reads Config.ini for the GameData section, loads
// Calligraphy.sip from Data/Game/, builds the prototype directory in memory).
//
// Once the database is up, we iterate the three prototype hierarchies we care
// about (Power, Condition, Item) and emit (enumIdx, fullPath) lines.  The
// downstream `Generate*Names.ps1` scripts in the repo parse these into static
// Dictionary<uint, string> tables for the buff / item-quantity trackers.

Console.WriteLine($"PrototypeEnumDumper: starting -- working dir = {Environment.CurrentDirectory}");

if (!File.Exists("Data/Game/Calligraphy.sip"))
{
    Console.Error.WriteLine("ERROR: Data/Game/Calligraphy.sip not found in working directory.");
    Console.Error.WriteLine("Run this EXE from a directory that contains:");
    Console.Error.WriteLine("  Config.ini");
    Console.Error.WriteLine("  Data/Game/Calligraphy.sip");
    Console.Error.WriteLine("The csproj build target copies these out of an MHServerEmu install for you;");
    Console.Error.WriteLine("if you moved the EXE, copy them across or rebuild in place.");
    Environment.Exit(1);
}

// PakFileSystem has to be initialized BEFORE the GameDatabase static ctor runs --
// the ctor calls DataDirectory.Initialize() which calls PakFileSystem.LoadFromPak()
// which NREs if the PakFile[] hasn't been built yet.  MHServerEmu's main ServerApp.cs
// does this two-step explicitly; we mirror it here so we don't rely on the order
// that .NET happens to JIT static ctors in.
var sw = System.Diagnostics.Stopwatch.StartNew();
if (!MHServerEmu.Games.GameData.PakFileSystem.Instance.Initialize())
{
    Console.Error.WriteLine("ERROR: PakFileSystem.Initialize() returned false -- the .sip files probably aren't in Data/Game/.");
    Environment.Exit(2);
}
Console.WriteLine($"PakFileSystem initialized in {sw.ElapsedMilliseconds} ms");

// Force-init the database.  The static ctor does all the heavy lifting; touching
// any public property is enough.  Wall-clock cost on a warm SSD is ~5-15 seconds.
sw.Restart();
_ = GameDatabase.IsInitialized;
sw.Stop();
Console.WriteLine($"GameDatabase initialized in {sw.ElapsedMilliseconds} ms");

var dir = GameDatabase.DataDirectory;

// Emit one prototype hierarchy.  For each prototype: get its wire-format enum
// index (the same uint that shows up in NetMessageAddCondition's archive as
// creatorPowerProtoRef, in EntityCreate's baseData as the entity proto idx, etc.)
// plus its full path string.  Output is sorted by enum index so diffs across
// dumps are stable.
static void DumpHierarchy<T>(string outputPath, DataDirectory dir) where T : Prototype
{
    var rows = new System.Collections.Generic.List<(int idx, string path)>();
    foreach (PrototypeId protoId in dir.IteratePrototypesInHierarchy<T>())
    {
        // Use the ROOT Prototype enum -- that's what Serializer.Transfer(ref PrototypeId)
        // writes on the wire.  GetPrototypeEnumValue<T>(...) where T is the concrete type
        // would give us a SEPARATE numbering scoped to that hierarchy (good for sanity
        // checks but not what shows up on the wire).
        int idx = dir.GetPrototypeEnumValue<Prototype>(protoId);
        string path = GameDatabase.GetPrototypeName(protoId);
        rows.Add((idx, path));
    }
    rows.Sort((a, b) => a.idx.CompareTo(b.idx));

    using var w = new StreamWriter(outputPath);
    w.WriteLine($"// Auto-generated by PrototypeEnumDumper.  {rows.Count} entries.");
    w.WriteLine($"// Hierarchy: {typeof(T).Name}");
    w.WriteLine($"// Format: <enumIdx>u, // <path>");
    foreach (var (idx, path) in rows)
        w.WriteLine($"  {idx}u,  // {path}");
    Console.WriteLine($"Wrote {rows.Count,6} entries to {outputPath}");
}

DumpHierarchy<PowerPrototype>("powers.txt", dir);
DumpHierarchy<ConditionPrototype>("conditions.txt", dir);
DumpHierarchy<ItemPrototype>("items.txt", dir);

// SECOND power dump, keyed by the POWER-SPECIFIC enum instead of the root one.  Important:
// MHServerEmu has two parallel prototype-enum spaces in play on the wire:
//   * NetMessagePowerResult uses Serializer.TransferPrototypeEnum<PowerPrototype> -- a
//     compact enum that only counts PowerPrototype instances (indices 1..~17k).
//   * NetMessageAddCondition's creatorPowerProtoRef uses Serializer.Transfer(ref PrototypeId)
//     which writes the ROOT Prototype enum (indices 1..~90k, every prototype type).
// Same power, two different numbers in the two messages.  We need name tables for both --
// powers-by-power-enum.txt feeds DpsMeter's MY POWERS table (damage events), powers.txt
// (already emitted above) feeds BuffTracker (buff sources).
{
    var rows = new System.Collections.Generic.List<(int idx, string path)>();
    foreach (PrototypeId protoId in dir.IteratePrototypesInHierarchy<PowerPrototype>())
    {
        int idx = dir.GetPrototypeEnumValue<PowerPrototype>(protoId);   // <-- power-specific enum
        string path = GameDatabase.GetPrototypeName(protoId);
        rows.Add((idx, path));
    }
    rows.Sort((a, b) => a.idx.CompareTo(b.idx));
    using var w = new StreamWriter("powers-by-power-enum.txt");
    w.WriteLine($"// Auto-generated by PrototypeEnumDumper.  {rows.Count} entries.");
    w.WriteLine($"// Hierarchy: PowerPrototype, keyed by GetPrototypeEnumValue<PowerPrototype>");
    w.WriteLine($"// Use this for damage events (NetMessagePowerResult.powerProtoRef).");
    w.WriteLine($"// Format: <enumIdx>u, // <path>");
    foreach (var (idx, path) in rows)
        w.WriteLine($"  {idx}u,  // {path}");
    Console.WriteLine($"Wrote {rows.Count,6} entries to powers-by-power-enum.txt");
}

// "All prototypes" dump.  Pulls in everything in the Prototype hierarchy (the root type),
// which is what the wire's prototype-enum-index is keyed against -- i.e. some damage
// events might reference a prototype that isn't a PowerPrototype subclass on this server's
// data version (a MissilePower might be flattened to a different parent, an alt-hero costume
// power lives somewhere we don't expect, etc).  Output is large (~50-70k entries) but easy
// to grep when "where does enum index X live?" comes up.
{
    var rows = new System.Collections.Generic.List<(int idx, string path)>();
    foreach (PrototypeId protoId in dir.IterateAllPrototypes())
    {
        int idx = dir.GetPrototypeEnumValue<Prototype>(protoId);
        string path = GameDatabase.GetPrototypeName(protoId);
        rows.Add((idx, path));
    }
    rows.Sort((a, b) => a.idx.CompareTo(b.idx));
    using var w = new StreamWriter("all-prototypes.txt");
    w.WriteLine($"// Auto-generated by PrototypeEnumDumper.  {rows.Count} entries.");
    w.WriteLine($"// Hierarchy: Prototype (root) -- includes EVERY prototype the server knows");
    w.WriteLine($"// Format: <enumIdx>u, // <path>");
    foreach (var (idx, path) in rows)
        w.WriteLine($"  {idx}u,  // {path}");
    Console.WriteLine($"Wrote {rows.Count,6} entries to all-prototypes.txt");
}

Console.WriteLine("Done.");
