using System.Collections.Generic;

namespace MarvelHeroes.DpsMeter.Services;

/// <summary>
/// Maps a condition prototype's enum index to a human-readable display name --
/// e.g. <c>55311u -&gt; "Team Buff Empowered 5 Seconds"</c>.  Surfaced in the buff-tracker
/// diagnostic log and (eventually) the active-buffs UI strip so users see "Empowered" instead
/// of "0xD80F".
///
/// <para>Generated by <c>scripts/GeneratePrototypeNames.ps1</c> from the condition dump file emitted
/// by <c>scripts/PrototypeEnumDumper</c>.  Re-run after pulling a fresh dump from a different
/// Calligraphy.sip version.  Names are auto-derived from the path basename with CamelCase
/// split for readability; for tricky cases edit this file directly or refine the cleanup
/// heuristics in the generator.</para>
///
/// <para>The dictionary is large (thousands of entries) but compiles fast and adds negligible
/// startup cost -- the dictionary literal is hoisted into a static field and the hash buckets
/// build once on first access.</para>
/// </summary>
internal static class ConditionNames
{
    /// <summary>Returns the display name for <paramref name="prototypeEnumIndex"/>, or
    /// <c>null</c> when the index is unmapped (older Calligraphy version, custom server, or
    /// a non-existent prototype id).  Callers should fall back to printing the raw hex id in
    /// that case so logs stay searchable.</summary>
    public static string? Get(uint prototypeEnumIndex)
        => s_names.TryGetValue(prototypeEnumIndex, out var n) ? n : null;

    private static readonly Dictionary<uint, string> s_names = new()
    {
        {     270u, "Pv P Shop Max Spirit Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopMaxSpiritBuffCondition.prototype
        {     279u, "CW Loot Power Up Effect IM Crossbones" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMCrossbones.prototype
        {    1598u, "Flask Of Movement Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfMovementCondition.prototype
        {    1838u, "CW Loot Power Up Effect IM Magneto" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMMagneto.prototype
        {    1968u, "Ao S Team SHIELD Mandarin Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDMandarinPowerUpEffect.prototype
        {    2692u, "Heroic Death Penalty" },  // Powers/Blueprints/Conditions/HeroicDeathPenalty.prototype
        {    4150u, "Stack Of Newspaper1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/StackOfNewspaper1HourCondition.prototype
        {    4242u, "XP2 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XP2HoursCondition.prototype
        {    4499u, "Mysterious Concoction Condition2" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition2.prototype
        {    5877u, "Rush XP4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/RushXP4HourCondition.prototype
        {    6153u, "Loot Power Up Effect Octopus" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectOctopus.prototype
        {    6263u, "Hamburger1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/Hamburger1HourCondition.prototype
        {    6492u, "Ao S Team Hydra Ultron Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraUltronPowerUpEffect.prototype
        {    6572u, "CW Loot Power Up Effect Cap Lady Deathstrike" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapLadyDeathstrike.prototype
        {    6616u, "Holo Sim Potion1 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/HoloSimPotion1Condition.prototype
        {    6670u, "Combo Bar4 Stack Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/ComboBar4StackCondition.prototype
        {    6772u, "Ao S Team SHIELD Gorgon Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDGorgonPowerUpEffect.prototype
        {    7027u, "XP24 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XP24HoursCondition.prototype
        {    7270u, "Rush SIF1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/RushSIF1HourCondition.prototype
        {    9062u, "Newspaper E Condition Power" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/NewspaperEConditionPower.prototype
        {    9342u, "Odins Bounty Event Power Condition" },  // Events/GlobalEvents/EventPowerConditions/OdinsBountyEventPowerCondition.prototype
        {    9486u, "XP720 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XP720HoursCondition.prototype
        {    9888u, "Cupcake1 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/Cupcake1Condition.prototype
        {   11059u, "Odin Boost2 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/OdinBoost2HourCondition.prototype
        {   11269u, "Hit React Condition Stun Chance" },  // Powers/Blueprints/Conditions/HitReactConditionStunChance.prototype
        {   11996u, "Live Tune Credits Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneCreditsDisplayCondition.prototype
        {   12322u, "Ao S Team Hydra Taskmaster Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraTaskmasterPowerUpEffect.prototype
        {   13434u, "Winter Boost3 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/WinterBoost3HourCondition.prototype
        {   13468u, "Summer Event Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/SummerEventPowerUpEffect.prototype
        {   13674u, "Mysterious Concoction Condition5" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition5.prototype
        {   13756u, "Team Iron Man Potion2 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamIronManPotion2Condition.prototype
        {   13951u, "Rarity168 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity168HoursCondition.prototype
        {   14147u, "Mug Of Grog1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MugOfGrog1HourCondition.prototype
        {   14268u, "Live Tune XP Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneXPDisplayCondition.prototype
        {   14642u, "Special Item Find24 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind24HoursCondition.prototype
        {   15337u, "Team Cap Potion2 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamCapPotion2Condition.prototype
        {   15960u, "SHIELD Supply Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/SHIELDSupplyBoostCondition.prototype
        {   16141u, "Pv P Shop Spirit Regen Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopSpiritRegenBuffCondition.prototype
        {   17128u, "CW Loot Power Up Effect Cap Bullseye" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapBullseye.prototype
        {   17245u, "zzz Combo Bar1 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/zzzComboBar1HCondition.prototype
        {   17299u, "Mysterious Concoction Condition9" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition9.prototype
        {   17582u, "CW Loot Power Up Effect Cap Shocker" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapShocker.prototype
        {   17659u, "CW Loot Power Up Effect IM Kirigi" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMKirigi.prototype
        {   18103u, "Ao S Team SHIELD Kingpin Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDKingpinPowerUpEffect.prototype
        {   18406u, "Pv P Shop Lifesteal Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopLifestealBuffCondition.prototype
        {   18779u, "Rush Rarity1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RushRarity1HourCondition.prototype
        {   18868u, "Live Tune SIF Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneSIFDisplayCondition.prototype
        {   18900u, "Penta2 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Penta2HourCondition.prototype
        {   20241u, "LE Rush Rarity4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SeasonalLE/Conditions/LERushRarity4HourCondition.prototype
        {   20518u, "Assemble Boost XP Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Assemble/Conditions/AssembleBoostXPCondition.prototype
        {   20533u, "RIF Gifty Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RIFGiftyCondition.prototype
        {   20643u, "Loot Power Up Effect Man Ape" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectManApe.prototype
        {   20694u, "Rarity Treasure Hunter Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RarityTreasureHunterCondition.prototype
        {   21161u, "CW Loot Power Up Effect Cap Hood" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapHood.prototype
        {   21426u, "Holo Sim Potion4 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/HoloSimPotion4Condition.prototype
        {   21694u, "Shop Revive1 Condition" },  // Powers/ItemPowers/ItemConditions/ShopRevive1Condition.prototype
        {   21876u, "Reputation Loot Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/ReputationLootBoostCondition.prototype
        {   21997u, "Fortune Card Boost Itm Find Condition" },  // Powers/ItemPowers/ItemConditions/FortuneCardBoostItmFindCondition.prototype
        {   22005u, "CW Loot Power Up Effect IM Hood" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMHood.prototype
        {   22284u, "CW Loot Power Up Effect Cap Kirigi" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapKirigi.prototype
        {   22381u, "Art223 Special Item Buff Condition" },  // Entity/Items/Artifacts/Art223SpecialItemBuffCondition.prototype
        {   22790u, "CW Loot Power Up Effect Cap Sinister" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapSinister.prototype
        {   22855u, "Special Item Find Gifty Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFindGiftyCondition.prototype
        {   22910u, "Rarity24 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity24HoursCondition.prototype
        {   23464u, "Team Iron Man Potion3 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamIronManPotion3Condition.prototype
        {   23590u, "Soulstone Holding Condition" },  // Entity/Items/Consumables/Prototypes/SoulstoneHoldingCondition.prototype
        {   24586u, "Live Tune Avatar XP Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneAvatarXPDisplayCondition.prototype
        {   25111u, "Triple2 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Triple2HourCondition.prototype
        {   26322u, "Loot Power Up Effect Crossbones" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectCrossbones.prototype
        {   26487u, "Rush Triple1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/RushTriple1HourCondition.prototype
        {   26945u, "SIF Boon1 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SIFBoon1HCondition.prototype
        {   27065u, "Team Up Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/TeamUpBoostCondition.prototype
        {   27347u, "XP Gifty Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XPGiftyCondition.prototype
        {   27516u, "Team Hydra2 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/TeamHydra2HCondition.prototype
        {   27578u, "Mysterious Concoction Condition10" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition10.prototype
        {   27844u, "Combo Bar1 Stack Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/ComboBar1StackCondition.prototype
        {   28088u, "Team Cap Potion3 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamCapPotion3Condition.prototype
        {   28731u, "Rarity Party Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RarityPartyCondition.prototype
        {   29006u, "Signed Photo1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/SignedPhoto1HourCondition.prototype
        {   29072u, "Ao S Team Hydra Hood Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraHoodPowerUpEffect.prototype
        {   29440u, "Live Tune RIF Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneRIFDisplayCondition.prototype
        {   30743u, "Fortune Card Boost Exp Condition" },  // Powers/ItemPowers/ItemConditions/FortuneCardBoostExpCondition.prototype
        {   30825u, "Surtur Encounter4 Energy Condition" },  // Powers/ItemPowers/ItemConditions/SurturEncounter4EnergyCondition.prototype
        {   31034u, "Guardians3 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Guardians3HourCondition.prototype
        {   31113u, "St Patricks Event Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/StPatricksEventPowerUpEffect.prototype
        {   31407u, "Danger Room Boost2 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/DangerRoomBoost2Condition.prototype
        {   31542u, "Special Item Find168 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind168HoursCondition.prototype
        {   31933u, "CW Loot Power Up Effect Cap Crossbones" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapCrossbones.prototype
        {   32373u, "CC React Condition" },  // Powers/Blueprints/Conditions/CCReactCondition.prototype
        {   32912u, "Damage Potion Condition" },  // Powers/ItemPowers/ItemConditions/DamagePotionCondition.prototype
        {   33222u, "Ao S Team Hydra Klrt Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraKlrtPowerUpEffect.prototype
        {   33359u, "Ao S Team Hydra Mandarin Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraMandarinPowerUpEffect.prototype
        {   33386u, "Omega Event Power Condition" },  // Events/GlobalEvents/EventPowerConditions/OmegaEventPowerCondition.prototype
        {   33835u, "Loot Power Up Effect Dr Doom" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectDrDoom.prototype
        {   34440u, "Loot Power Up Effect Vulture" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectVulture.prototype
        {   34551u, "Currency Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/CurrencyBoostCondition.prototype
        {   34725u, "Holo Sim Potion5 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/HoloSimPotion5Condition.prototype
        {   35074u, "CW Loot Power Up Effect IM Gorgon" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMGorgon.prototype
        {   35269u, "Rush Credits1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/CreditFind/Conditions/RushCredits1HourCondition.prototype
        {   35593u, "CW Loot Power Up Effect Cap Batroc" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapBatroc.prototype
        {   36387u, "Minor XP30 Min Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ExperienceBoost/MinorXP30MinCondition.prototype
        {   36746u, "Ao S Team SHIELD Shocker Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDShockerPowerUpEffect.prototype
        {   36857u, "Shop Boost XP1 Condition" },  // Powers/ItemPowers/ItemConditions/ShopBoostXP1Condition.prototype
        {   37116u, "Pv P Shop HP Regen Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopHPRegenBuffCondition.prototype
        {   37501u, "Hit React Condition Stun" },  // Powers/Blueprints/Conditions/HitReactConditionStun.prototype
        {   38211u, "i Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/iBoostCondition.prototype
        {   38804u, "Animal Balloon Buff Condition" },  // Powers/ItemPowers/ItemConditions/AnimalBalloonBuffCondition.prototype
        {   38908u, "CW Loot Power Up Effect Cap Mole Man" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapMoleMan.prototype
        {   39037u, "Avatar Synergy Condition" },  // Powers/Blueprints/Conditions/AvatarSynergyCondition.prototype
        {   39128u, "Ao S Team Hydra Crossbones Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraCrossbonesPowerUpEffect.prototype
        {   39415u, "Loot Power Up Effect Kurse" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectKurse.prototype
        {   39735u, "Pretzel1 Hour Condition" },  // Entity/Items/Consumables/Pretzel1HourCondition.prototype
        {   41609u, "CW Loot Power Up Effect IM Electro" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMElectro.prototype
        {   41672u, "Regular Damage Potion Condition" },  // Powers/ItemPowers/ItemConditions/RegularDamagePotionCondition.prototype
        {   41984u, "Newspaper C Condition Power" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/NewspaperCConditionPower.prototype
        {   42210u, "Pv P Shop Dodge Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopDodgeBuffCondition.prototype
        {   42443u, "Loot Power Up Effect Mr Hyde" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectMrHyde.prototype
        {   42535u, "Surtur Encounter4 Physical Conditio" },  // Powers/ItemPowers/ItemConditions/SurturEncounter4PhysicalConditio.prototype
        {   43354u, "Rarity2 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity2HoursCondition.prototype
        {   43823u, "CW Loot Power Up Effect IM Mandarin" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMMandarin.prototype
        {   43862u, "Ice Cream Bar Condition" },  // Entity/Items/Consumables/Prototypes/IceCreamBarCondition.prototype
        {   44420u, "Combo Bar2 Stack Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/ComboBar2StackCondition.prototype
        {   44814u, "CW Loot Power Up Effect Cap Red Skull" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapRedSkull.prototype
        {   45649u, "Shop Boost All Condition" },  // Powers/ItemPowers/ItemConditions/ShopBoostAllCondition.prototype
        {   45662u, "Mysterious Concoction Condition7" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition7.prototype
        {   45878u, "Delicious Pizza1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/DeliciousPizza1HourCondition.prototype
        {   46040u, "Loot Power Up Effect Hood" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectHood.prototype
        {   46307u, "Flask Of Health Greater Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfHealthGreaterCondition.prototype
        {   47019u, "Team Up Synergy Condition" },  // Powers/Blueprints/Conditions/TeamUpSynergyCondition.prototype
        {   47120u, "Vday Triple Gifty Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/VdayTripleGiftyCondition.prototype
        {   47219u, "Special Item Find72 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind72HoursCondition.prototype
        {   47994u, "Loot Power Up Effect Klrt" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectKlrt.prototype
        {   48535u, "Danger Room Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/DangerRoomBoostCondition.prototype
        {   48829u, "XP Party Power Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XPPartyPowerCondition.prototype
        {   48888u, "Team Cap Potion1 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamCapPotion1Condition.prototype
        {   48912u, "Credit Find2 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/CreditFind/Conditions/CreditFind2HoursCondition.prototype
        {   49195u, "Winter Event Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/WinterEventPowerUpEffect.prototype
        {   49797u, "Rush Credits4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/CreditFind/Conditions/RushCredits4HourCondition.prototype
        {   49832u, "Team SHIELD2 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/TeamSHIELD2HCondition.prototype
        {   50598u, "Team Iron Man Potion1 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamIronManPotion1Condition.prototype
        {   51228u, "Cowbell Condition" },  // Powers/Player/zzzBrevik/CowbellCondition.prototype
        {   51490u, "Attack And Movement Speed Condition" },  // Powers/ItemPowers/ItemConditions/AttackAndMovementSpeedCondition.prototype
        {   51823u, "Rush Orb Attract4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/OrbBoost/Conditions/RushOrbAttract4HourCondition.prototype
        {   51854u, "LE Rush Credits4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/CreditFind/Conditions/LERushCredits4HourCondition.prototype
        {   52017u, "Loot Power Up Effect Jugg" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectJugg.prototype
        {   52080u, "Credit Find70 Mins Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/CreditFind/Conditions/CreditFind70MinsCondition.prototype
        {   52725u, "Loot Power Up Effect TM" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectTM.prototype
        {   52771u, "CW Loot Power Up Effect Cap Kurse" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapKurse.prototype
        {   53965u, "Rarity70 Minute Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity70MinuteCondition.prototype
        {   54137u, "Box Of Keepsakes30min Condition" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/BoxOfKeepsakes30minCondition.prototype
        {   54196u, "Test Party Boost Condition" },  // Entity/Items/Consumables/Prototypes/Test/TestPartyBoostCondition.prototype
        {   54472u, "CW Loot Power Up Effect Cap Mandarin" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapMandarin.prototype
        {   54529u, "CW Loot Power Up Effect Cap Black Cat" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapBlackCat.prototype
        {   54693u, "Mysterious Concoction Condition1" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition1.prototype
        {   54906u, "Hit React Condition Immobilize" },  // Powers/Blueprints/Conditions/HitReactConditionImmobilize.prototype
        {   55332u, "CW Loot Power Up Effect IM Red Skull" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMRedSkull.prototype
        {   55485u, "Rarity72 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity72HoursCondition.prototype
        {   55681u, "Super Heroic Death Penalty" },  // Powers/Blueprints/Conditions/SuperHeroicDeathPenalty.prototype
        {   55752u, "CW Loot Power Up Effect IM Hyde" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMHyde.prototype
        {   56153u, "Special Item Find70 Min Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind70MinCondition.prototype
        {   56729u, "Loot Power Up Effect Mand" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectMand.prototype
        {   56797u, "Loot Power Up Effect Shock" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectShock.prototype
        {   57155u, "Loot Power Up Effect Mister" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectMister.prototype
        {   57568u, "Ao S Shocker Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSShockerPowerUpEffect.prototype
        {   58041u, "Rarity720 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/Rarity720HoursCondition.prototype
        {   58052u, "Odinboost3 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/Odinboost3HourCondition.prototype
        {   58784u, "Team Iron Man Potion4 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamIronManPotion4Condition.prototype
        {   58965u, "Pv P Shop Max HP Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopMaxHPBuffCondition.prototype
        {   59221u, "Assemble Boost RIF Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Assemble/Conditions/AssembleBoostRIFCondition.prototype
        {   59349u, "Live Tune Region XP Display Condition" },  // Powers/Blueprints/Conditions/LiveTuneRegionXPDisplayCondition.prototype
        {   59429u, "XP168 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XP168HoursCondition.prototype
        {   59876u, "Twin Affix Damage Share Condition" },  // Powers/EnemyPowers/AffixPowers/TwinAffixDamageShareCondition.prototype
        {   61265u, "Mystic Mayhem Event Power Condition" },  // Events/GlobalEvents/EventPowerConditions/MysticMayhemEventPowerCondition.prototype
        {   61903u, "SIF Party Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SIFPartyCondition.prototype
        {   62388u, "Team Iron Man Boost1 Week Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/TeamIronManBoost1WeekCondition.prototype
        {   63197u, "Team Cap Potion4 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/TeamCapPotion4Condition.prototype
        {   63255u, "XP Boon1 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XPBoon1HCondition.prototype
        {   63336u, "CW Loot Power Up Effect Cap Doc Oct" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapDocOct.prototype
        {   63609u, "BIF Credits1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/BIFCredits1HourCondition.prototype
        {   63754u, "Halloween Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/HalloweenPowerUpEffect.prototype
        {   63996u, "CW Loot Power Up Effect IM Juggernaut" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMJuggernaut.prototype
        {   64131u, "Potion Of Health Condition" },  // Powers/ItemPowers/ItemConditions/PotionOfHealthCondition.prototype
        {   64196u, "Summer Boost3 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/SummerBoost3HourCondition.prototype
        {   64657u, "Loot Power Up Effect Ultron" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectUltron.prototype
        {   65643u, "Flask Of Health Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfHealthCondition.prototype
        {   66049u, "XP72 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/XP72HoursCondition.prototype
        {   66067u, "Assemble Boost SIF Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Assemble/Conditions/AssembleBoostSIFCondition.prototype
        {   66106u, "CW Loot Power Up Effect Batroc" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectBatroc.prototype
        {   66111u, "Cupcake2 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/Cupcake2Condition.prototype
        {   66233u, "Loot Power Up Effect MODOK" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectMODOK.prototype
        {   66871u, "Combo Bar5 Stack Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/ComboBar5StackCondition.prototype
        {   67304u, "Ao S Team SHIELD Nick Fury Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDNickFuryPowerUpEffect.prototype
        {   67666u, "Bounty1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Bounty1HourCondition.prototype
        {   68579u, "Special Item Find2 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind2HoursCondition.prototype
        {   68623u, "Mysterious Concoction Condition6" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition6.prototype
        {   68694u, "Newspaper D Condition Power" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/NewspaperDConditionPower.prototype
        {   69197u, "Holo Sim Potion2 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/HoloSimPotion2Condition.prototype
        {   70514u, "Holo Sim Potion3 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Powers/HoloSimPotion3Condition.prototype
        {   71270u, "CW Loot Power Up Effect Cap Man Ape" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapManApe.prototype
        {   71544u, "Regular Haste Potion Condition" },  // Powers/ItemPowers/ItemConditions/RegularHastePotionCondition.prototype
        {   72268u, "Achievers Brew Condition" },  // Powers/ItemPowers/ItemConditions/AchieversBrewCondition.prototype
        {   72434u, "Splinter Boost3 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/SplinterBoost3HourCondition.prototype
        {   72537u, "Loot Power Up Effect Red Skull" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectRedSkull.prototype
        {   73037u, "CW Loot Power Up Effect IM Man Ape" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMManApe.prototype
        {   73751u, "Pv P Shop Crit Damage Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopCritDamageBuffCondition.prototype
        {   73976u, "Pv P Shop Attack Speed Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopAttackSpeedBuffCondition.prototype
        {   73992u, "Surtur Encounter4 Mental Condition" },  // Powers/ItemPowers/ItemConditions/SurturEncounter4MentalCondition.prototype
        {   74017u, "CW Loot Power Up Effect IM Nick Fury" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMNickFury.prototype
        {   74588u, "Pv P Shop Tenacity Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopTenacityBuffCondition.prototype
        {   74724u, "Mysterious Concoction Condition3" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition3.prototype
        {   74751u, "CW Loot Power Up Effect Cap Green Goblin" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapGreenGoblin.prototype
        {   75460u, "Ao S Team SHIELD Batroc Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDBatrocPowerUpEffect.prototype
        {   75527u, "Birthday Event Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/BirthdayEventPowerUpEffect.prototype
        {   75599u, "Cupcake3 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/Cupcake3Condition.prototype
        {   75806u, "Flask Of Spirit Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfSpiritCondition.prototype
        {   76166u, "Rarity Boon1 H Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RarityBoon1HCondition.prototype
        {   76854u, "CW Loot Power Up Effect IM Sinister" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMSinister.prototype
        {   77771u, "Flask Of Might Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfMightCondition.prototype
        {   78069u, "Newspaper B Condition Power" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/NewspaperBConditionPower.prototype
        {   78181u, "Ao S Team SHIELD Klrt Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamSHIELDKlrtPowerUpEffect.prototype
        {   78676u, "Patrol Boost Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/PatrolBoostCondition.prototype
        {   78820u, "Art215 Credit Find Buff Condition" },  // Entity/Items/Artifacts/Art215CreditFindBuffCondition.prototype
        {   78845u, "Omega Boost4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/OmegaBoost4HourCondition.prototype
        {   79736u, "Rush Rarity4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/ItemRarity/Conditions/RushRarity4HourCondition.prototype
        {   80077u, "Combo Bar3 Stack Condition" },  // Entity/Items/Consumables/Prototypes/GShop/SHIELDSupplyBoost/ComboBar3StackCondition.prototype
        {   80217u, "CW Loot Power Up Effect IM Kurse" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMKurse.prototype
        {   80575u, "Pv P Shop Move Speed Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopMoveSpeedBuffCondition.prototype
        {   81805u, "Pv P Shop Crit Chance Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopCritChanceBuffCondition.prototype
        {   82559u, "Newspaper A Condition Power" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/NewspaperAConditionPower.prototype
        {   82685u, "Shop Boost Item Find1 Condition" },  // Powers/ItemPowers/ItemConditions/ShopBoostItemFind1Condition.prototype
        {   82924u, "Orb Attraction70min Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/OrbBoost/Conditions/OrbAttraction70minCondition.prototype
        {   83084u, "Mysterious Concoction Condition4" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition4.prototype
        {   84245u, "XP1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ExperienceBoost/XP1HourCondition.prototype
        {   84249u, "Rush XP1 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/RushXP1HourCondition.prototype
        {   84639u, "Loot Power Up Effect Magno" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectMagno.prototype
        {   84877u, "Team Cap Boost1 Week Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/Jackpot/Conditions/TeamCapBoost1WeekCondition.prototype
        {   85241u, "ARMOR Event Power Condition" },  // Events/GlobalEvents/EventPowerConditions/ARMOREventPowerCondition.prototype
        {   85389u, "Cosmic Chaos Event Power Condition" },  // Events/GlobalEvents/EventPowerConditions/CosmicChaosEventPowerCondition.prototype
        {   85529u, "Loot Power Up Effect Kingpin" },  // Entity/Items/Orbs/PowerUps/Effects/LootPowerUpEffectKingpin.prototype
        {   86135u, "Special Item Find720 Hours Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/SpecialItemFind720HoursCondition.prototype
        {   86181u, "Hit React Condition" },  // Powers/Blueprints/Conditions/HitReactCondition.prototype
        {   86782u, "Mysterious Concoction Condition8" },  // Entity/Items/Consumables/Prototypes/AchievementRewards/ItemRewards/MysteriousConcoctionCondition8.prototype
        {   87517u, "Holo Sim Potion6 Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/XPBoost/Conditions/HoloSimPotion6Condition.prototype
        {   87960u, "CW Loot Power Up Effect Cap Taskmaster" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapTaskmaster.prototype
        {   88273u, "CW Loot Power Up Effect IM Kingpin" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMKingpin.prototype
        {   88825u, "Triple4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Triple4HourCondition.prototype
        {   89851u, "Pv P Shop Damage Buff Condition" },  // Powers/PvPPowers/ShopPowers/Redacted/PvPShopDamageBuffCondition.prototype
        {   90201u, "Valentines Event Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/ValentinesEventPowerUpEffect.prototype
        {   90289u, "CW Loot Power Up Effect Cap Juggernaut" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectCapJuggernaut.prototype
        {   90654u, "Ao S Team Hydra Juggernaut Power Up Effect" },  // Entity/Items/Orbs/PowerUps/Effects/AoSTeamHydraJuggernautPowerUpEffect.prototype
        {   90765u, "Flask Of Might Greater Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfMightGreaterCondition.prototype
        {   91648u, "Rush SIF4 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/SpecialItemFind/Conditions/RushSIF4HourCondition.prototype
        {   92547u, "Flask Of Spirit Greater Condition" },  // Powers/ItemPowers/ItemConditions/FlaskOfSpiritGreaterCondition.prototype
        {   92968u, "CW Loot Power Up Effect IM Shocker" },  // Entity/Items/Orbs/PowerUps/Effects/CWLootPowerUpEffectIMShocker.prototype
        {   93080u, "Quad2 Hour Condition" },  // Entity/Items/Consumables/Prototypes/GShop/ZZZDeprecated/DeprecatedConsumables/TripleBoost/Conditions/Quad2HourCondition.prototype
    };
}
