using System.Collections.Generic;

namespace MarvelHeroes.DpsMeter.Services;

/// <summary>
/// Hardcoded map <c>prototypeEnumIndex → hero display name</c> used by the DPS overlay title.
///
/// <para>
/// The prototype enum index is the value transported on the wire inside
/// <c>NetMessageEntityCreate.baseData</c> via <c>TransferPrototypeEnum&lt;EntityPrototype&gt;</c>.
/// It equals the 1-based position of the avatar's <c>PrototypeDataRefRecord</c> inside the
/// sorted-by-<c>PrototypeId</c> list of every <c>EntityPrototype</c>-descendant record that
/// <c>DataDirectory.InitializeHierarchyCache</c> builds at server startup.
/// </para>
///
/// <para>
/// The table below was generated by <c>OpenCalligraphy.AvatarEnumDumper</c> against
/// <c>Calligraphy.sip</c> from MHServerEmu (game build 1.52, 21,689 total EntityPrototype
/// descendants).  Indices are deterministic for a given data pack, so if the game data pack
/// ever changes, re-run the dumper and replace this block:
/// </para>
///
/// <code>
/// dotnet run --project OpenCalligraphy/src/OpenCalligraphy.AvatarEnumDumper -- \
///     "C:\MrvelHeroes\MHServerEmu\Data\Game\Calligraphy.sip" --out avatar-enum.generated.cs
/// </code>
/// </summary>
internal static class HeroPrototypes
{
    /// <summary>
    /// All <c>AvatarPrototype</c> enum indices known at build time.  Shipping heroes are listed
    /// first (by alphabetical name); development / test-only avatars follow so they still render
    /// with a name if the wire ever mentions them (instead of the <c>Hero #N</c> placeholder).
    /// </summary>
    public static readonly IReadOnlyDictionary<uint, string> Names = new Dictionary<uint, string>
    {
        // ── Shipping heroes (Entity/Characters/Avatars/Shipping/*.prototype) ────────────────────
        { 15446u, "Angela" },
        { 21324u, "Ant-Man" },
        { 20043u, "Beast" },
        {  7383u, "Black Bolt" },
        { 14718u, "Black Cat" },
        {   551u, "Black Panther" },
        { 11925u, "Black Widow" },
        {  7269u, "Blade" },
        { 19033u, "Cable" },
        { 12500u, "Captain America" },
        {  1964u, "Carnage" },
        { 13120u, "Colossus" },
        {  7795u, "Cyclops" },
        { 13656u, "Daredevil" },
        {  1992u, "Deadpool" },
        { 11399u, "Doctor Strange" },
        { 20880u, "Dr. Doom" },
        {  9310u, "Elektra" },
        {   493u, "Emma Frost" },
        {  7631u, "Gambit" },
        { 10883u, "Ghost Rider" },
        {  8295u, "Green Goblin" },
        {  4307u, "Hawkeye" },
        {  9739u, "Hulk" },
        {  8271u, "Human Torch" },
        { 12123u, "Iceman" },
        { 14402u, "Invisible Woman" },
        { 15544u, "Iron Fist" },
        {   507u, "Iron Man" },
        { 14630u, "Jean Grey" },
        { 15363u, "Juggernaut" },
        {  1410u, "Kitty Pryde" },
        { 16960u, "Loki" },
        { 16879u, "Luke Cage" },
        { 18494u, "Magik" },
        { 10322u, "Magneto" },
        {  5014u, "Moon Knight" },
        { 20689u, "Mr. Fantastic" },
        { 20579u, "Ms. Marvel" },
        {  2623u, "Nick Fury" },
        { 21346u, "Nightcrawler" },
        {    80u, "Nova" },
        {   859u, "Psylocke" },
        {  5481u, "Punisher" },
        { 10414u, "Rocket Raccoon" },
        {  7724u, "Rogue" },
        { 16266u, "Scarlet Witch" },
        { 14556u, "She-Hulk" },
        { 13100u, "Silver Surfer" },
        { 11020u, "Spider-Man" },
        { 15433u, "Squirrel Girl" },
        {  6386u, "Star-Lord" },
        {  8044u, "Storm" },
        { 15955u, "Taskmaster" },
        { 16469u, "Thing" },
        {  9328u, "Thor" },
        {  2348u, "Ultron" },
        { 18395u, "Venom" },
        {  4770u, "Vision" },
        { 10183u, "War Machine" },
        { 17750u, "Winter Soldier" },
        { 15574u, "Wolverine" },
        {  9000u, "X-23" },

        // ── Non-shipping / test-only avatars (surfaced as-is if the wire ever mentions them) ────
        {   854u, "<Avatar Default>" },
        { 15651u, "testPlayable: SunTribeMale" },
        { 18784u, "testPlayable: AIMAgentBrawler" },
        {  6414u, "testPlayable: AIMAgentGunner" },
        { 18156u, "testPlayable: AIMOperativeBrawler" },
        { 15487u, "testPlayable: AIMOperativeGunner" },
        {  7877u, "testPlayable: BroodSoldier" },
        {   619u, "testPlayable: FallPeopleMale" },
        {  4206u, "testPlayable: HydraAgent" },
        {  3510u, "testPlayable: HydraAgentB" },
        { 19836u, "testPlayable: HydraAgentC" },
        { 19078u, "testPlayable: HydraGunner" },
        { 13488u, "testPlayable: HydraPowerBrawler" },
        {  1198u, "testPlayable: KingLizard" },
        { 15508u, "testPlayable: Lavaman" },
        { 19523u, "testPlayable: MariaHill" },
        { 13751u, "testPlayable: Moloid" },
        { 12286u, "testPlayable: Raptor" },
        { 11916u, "testPlayable: Selene" },
        {  1289u, "testPlayable: ShieldAgentA" },
        { 12802u, "testPlayable: ShieldAgentB" },
        {  7152u, "zzzBrevikOLD" },
        { 18525u, "zzzBrevikRoundTwo" },
    };

    /// <summary>
    /// Avatar <c>PrototypeDataRef</c> → hero display name.  Mirrors <see cref="Names"/> but keyed
    /// on the full 64-bit prototype-ref hash instead of the enum index. Used by the DPS meter's
    /// community-slot fallback: <c>NetMessageModifyCommunityMember.broadcast.slots[0].avatarRefId</c>
    /// carries a remote player's currently-selected avatar as a DataRef, and that's our only
    /// reliable signal for "which hero is player X on right now?" when the app was launched mid-
    /// session and we missed their <c>NetMessageEntityCreate</c> (so the dbId → avatarEntityId
    /// map was never populated via the EntityCreate-scan path).
    ///
    /// Auto-generated from <c>avatar-dataref.generated.cs</c>; regenerate via
    /// <c>OpenCalligraphy.AvatarEnumDumper --out-avatar-datarefs avatar-dataref.generated.cs</c>
    /// whenever the game-data pak changes.
    /// </summary>
    public static readonly IReadOnlyDictionary<ulong, string> NamesByDataRef = new Dictionary<ulong, string>
    {
        { 0xB6234EED0F231466ul, "Angela" },
        { 0xFBA4711F104C147Dul, "Ant-Man" },
        { 0xEC9D8B5DFB5B140Dul, "Beast" },
        { 0x565F6AE54ED015ACul, "Black Bolt" },
        { 0xADF51B35388D1533ul, "Black Cat" },
        { 0x06564601924E16EDul, "Black Panther" },
        { 0x8CC6F26865A81625ul, "Black Widow" },
        { 0x55336B65FA6413F6ul, "Blade" },
        { 0xE0F4DAE6FA4613F5ul, "Cable" },
        { 0x935A0D02C0BD17B0ul, "Captain America" },
        { 0x16D3A3D323DA14CFul, "Carnage" },
        { 0x9A4B5A6D3C5B1579ul, "Colossus" },
        { 0x5B358443261914FBul, "Cyclops" },
        { 0xA13392F14F1115AEul, "Daredevil" },
        { 0x170A649D397B1546ul, "Deadpool" },
        { 0x86AA66A7ACBF177Dul, "Doctor Strange" },
        { 0xF657A69A108F1483ul, "Dr. Doom" },
        { 0x6E27541D250E14E6ul, "Elektra" },
        { 0x05BB269050B015CCul, "Emma Frost" },
        { 0x597C27CE0F9A1472ul, "Gambit" },
        { 0x8072076D67621639ul, "Ghost Rider" },
        { 0x615B57B47C46168Aul, "Green Goblin" },
        { 0x31ED335B255C14ECul, "Hawkeye" },
        { 0x731AD1F5E84A13B2ul, "Hulk" },
        { 0x6117E51E67591637ul, "Human Torch" },
        { 0x8F0441460F55146Bul, "Iceman" },
        { 0xAA221ADCC46F17E5ul, "Invisible Woman" },
        { 0xB75DE8093BD6156Cul, "Iron Fist" },
        { 0x05DA80FA25DA14F2ul, "Iron Man" },
        { 0xACEADBE23A3D1553ul, "Jean Grey" },
        { 0xB5422B28673E163Aul, "Juggernaut" },
        { 0x1045462969561657ul, "Kitty Pryde" },
        { 0xC81ACE5CE81213ADul, "Loki" },
        { 0xC7366F5439B1153Ful, "Luke Cage" },
        { 0xDA7D2D96FB3B1407ul, "Magik" },
        { 0x7982779F251D14E9ul, "Magneto" },
        { 0x3A3CDE1B679F163Cul, "Moon Knight" },
        { 0xF42279A37D6A169Aul, "Mr. Fantastic" },
        { 0xF302BFB83B9D1565ul, "Ms. Marvel" },
        { 0x1E811C003B711569ul, "Nick Fury" },
        { 0xFBEB4EE8945E1708ul, "Nightcrawler" },
        { 0x010007A6E85A13B2ul, "Nova" },
        { 0x0A0E983B3C121568ul, "Psylocke" },
        { 0x401147E73C17156Cul, "Punisher" },
        { 0x7AB66E9AAB7D176Bul, "Rocket Raccoon" },
        { 0x5A68AFBFFC981420ul, "Rogue" },
        { 0xC012227894AE170Bul, "Scarlet Witch" },
        { 0xAC02ACD725C514F2ul, "She-Hulk" },
        { 0x9A17B8BC96D3172Aul, "Silver Surfer" },
        { 0x82274FBD509915C1ul, "Spider-Man" },
        { 0xB5ECAD9F96A21723ul, "Squirrel Girl" },
        { 0x4ADB8B743BEE1569ul, "Star-Lord" },
        { 0x5E41A871FD891433ul, "Storm" },
        { 0xBC840AF5678E163Dul, "Taskmaster" },
        { 0xC25F2D0EFC301418ul, "Thing" },
        { 0x6E5392AEE8BA13BBul, "Thor" },
        { 0x1B721266125714A2ul, "Ultron" },
        { 0xD95AFE77FCB31423ul, "Venom" },
        { 0x373EABA611B71496ul, "Vision" },
        { 0x781190EC65EC161Dul, "War Machine" },
        { 0xD1C3A38AADCF1789ul, "Winter Soldier" },
        { 0xB7B63FFD522B15D9ul, "Wolverine" },
        { 0x6A118FB0CFD712DBul, "X-23" },
    };

    /// <summary>
    /// Returns <c>"Blade"</c> / <c>"Iron Man"</c> / … for known indices, <c>"Hero #N"</c> for
    /// unknown indices, or <c>"—"</c> when we haven't detected the hero yet (index 0).
    /// </summary>
    public static string GetDisplayName(uint prototypeEnumIndex)
    {
        if (prototypeEnumIndex == 0) return "—";
        return Names.TryGetValue(prototypeEnumIndex, out var name)
            ? name
            : $"Hero #{prototypeEnumIndex}";
    }

    /// <summary>
    /// Community-slot variant: returns a pretty hero name for the given avatar
    /// <c>PrototypeDataRef</c> (the 64-bit hash on the wire), or empty string if the ref doesn't
    /// correspond to a known shipping hero. Callers pass this to the DPS meter's dbId↔entityId
    /// binder as part of the mid-session nickname fallback.
    /// </summary>
    public static string GetDisplayNameByDataRef(ulong avatarDataRef)
    {
        if (avatarDataRef == 0) return string.Empty;
        return NamesByDataRef.TryGetValue(avatarDataRef, out var name) ? name : string.Empty;
    }

    /// <summary>Used by <see cref="DpsMeter"/> to log unknown indices exactly once per session
    /// so the user sees what number to copy into <see cref="Names"/> above.</summary>
    public static bool IsKnown(uint prototypeEnumIndex) => Names.ContainsKey(prototypeEnumIndex);
}
