#requires -Version 5.1

<#
.SYNOPSIS
    Generate Services/PowerNames.cs or Services/ConditionNames.cs from the prototype dump
    produced by PrototypeEnumDumper.

.DESCRIPTION
    Reads a text file shaped like the PrototypeEnumDumper output:

        // Auto-generated by PrototypeEnumDumper.  N entries.
        // Hierarchy: PowerPrototype
          3u,  // Powers/Player/Thor/Rework/BasicMeleeThunderclapCombo.prototype
          4u,  // Powers/Player/RocketRaccoon/Talents/Talent5Grenades.prototype
          ...

    Derives a human-readable display name from each prototype's path basename and emits a
    static Dictionary<uint, string> at the requested output path so the buff tracker can
    surface "BasicMeleeThunderclapCombo" -> "Basic Melee Thunderclap Combo" instead of
    showing raw enum ids like "0xD80F" in the diagnostic log.

    Cleanup heuristics:
      - Take the basename (last path segment, with .prototype stripped)
      - CamelCase -> "Camel Case" (insert space before each CapsRun + before the last cap
        of an all-caps run that's followed by lowercase, so "RedSuitBuff" -> "Red Suit Buff"
        and "PvPShopDodge" -> "Pv P Shop Dodge"... hm, that last one is awkward but
        consistent.  Heroes' naming convention is inconsistent enough that no single rule
        produces beautiful output for every case -- we accept some awkwardness in exchange
        for a deterministic, debug-readable pipeline.)
      - Collapse repeated whitespace; trim
      - Tag the output with the original PATH-section prefix (Player / Enemy / Item / etc)
        so the log line is unambiguous when the basename alone is generic
        ("BasicMelee" vs "BasicMelee").

.PARAMETER InputFile
    Path to the PrototypeEnumDumper output (e.g. powers.txt or conditions.txt).

.PARAMETER OutputFile
    Path to write the generated .cs file (e.g. PowerNames.cs).

.PARAMETER ClassName
    C# class name to use in the output file (e.g. "PowerNames" or "ConditionNames").

.PARAMETER Kind
    Human-readable label for the doc comments ("power", "condition").  Affects only the
    summary text in the generated file.

.PARAMETER DryRun
    Don't write the output; print stats and a sample of cleaned names to the console.

.EXAMPLE
    .\scripts\GeneratePrototypeNames.ps1 `
        -InputFile  scripts\PrototypeEnumDumper\bin\Release\net8.0\powers.txt `
        -OutputFile MarvelHeroes.DpsMeter\Services\PowerNames.cs `
        -ClassName  PowerNames -Kind power

.EXAMPLE
    .\scripts\GeneratePrototypeNames.ps1 `
        -InputFile  scripts\PrototypeEnumDumper\bin\Release\net8.0\conditions.txt `
        -OutputFile MarvelHeroes.DpsMeter\Services\ConditionNames.cs `
        -ClassName  ConditionNames -Kind condition
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string] $InputFile,
    [Parameter(Mandatory=$true)][string] $OutputFile,
    [Parameter(Mandatory=$true)][string] $ClassName,
    [Parameter(Mandatory=$true)][ValidateSet('power','condition')][string] $Kind,
    [switch] $DryRun
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $InputFile)) {
    throw "Input file not found: $InputFile.  Run PrototypeEnumDumper first."
}

# Dumper line format: <leading spaces><digits>u,<whitespace>// <path>.prototype
# Captures: 1 = enum index, 2 = full path without .prototype.
$lineRegex = '^\s+(\d+)u,\s*//\s*(\S+)\.prototype\s*$'

function Clean-Name([string] $rawBasename, [string] $fullPath) {
    $n = $rawBasename

    # CamelCase -> "Camel Case".  See doc comment for rationale.  Use -creplace (case-
    # sensitive) so [A-Z] doesn't match lowercase.
    $n = [Regex]::Replace($n, '([a-z\d])([A-Z])', '$1 $2')
    $n = [Regex]::Replace($n, '([A-Z]+)([A-Z][a-z])', '$1 $2')

    # Collapse repeated whitespace, trim.
    $n = ($n -replace '\s+', ' ').Trim()
    return $n
}

# ── Parse the dump --------------------------------------------------------
$entries = New-Object System.Collections.Generic.List[psobject]
foreach ($line in [System.IO.File]::ReadAllLines($InputFile)) {
    $m = [Regex]::Match($line, $lineRegex)
    if (-not $m.Success) { continue }
    $idx  = [uint32] $m.Groups[1].Value
    $path = $m.Groups[2].Value
    $base = $path.Split('/')[-1]
    $name = Clean-Name $base $path
    $entries.Add([pscustomobject]@{
        Index    = $idx
        Path     = $path
        Basename = $base
        Name     = $name
    }) | Out-Null
}

if ($entries.Count -eq 0) {
    throw "No prototype entries matched in $InputFile.  Check that the file is a PrototypeEnumDumper output."
}

# De-dup by index just in case the dumper emitted duplicates (shouldn't happen but defensive).
$byIndex = @{}
foreach ($e in $entries) {
    if (-not $byIndex.ContainsKey($e.Index)) {
        $byIndex[$e.Index] = $e
    }
}

Write-Host ("Parsed {0} {1} entries from {2} ({3} unique indices)" -f $entries.Count, $Kind, (Split-Path -Leaf $InputFile), $byIndex.Count)
Write-Host ""
Write-Host "Sample (first 15 cleaned names):"
$entries | Select-Object -First 15 | ForEach-Object {
    "  {0,7}  {1,-55}  =>  {2}" -f $_.Index, $_.Basename, $_.Name
} | Write-Host

if ($DryRun) {
    Write-Host ""
    Write-Host "Dry run -- output file NOT written."
    return
}

# ── Emit the .cs file -----------------------------------------------------
$kindCap = (Get-Culture).TextInfo.ToTitleCase($Kind)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('using System.Collections.Generic;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace MarvelHeroes.DpsMeter.Services;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine("/// Maps a $Kind prototype's enum index to a human-readable display name --")
[void]$sb.AppendLine("/// e.g. <c>55311u -&gt; ""Team Buff Empowered 5 Seconds""</c>.  Surfaced in the buff-tracker")
[void]$sb.AppendLine('/// diagnostic log and (eventually) the active-buffs UI strip so users see "Empowered" instead')
[void]$sb.AppendLine('/// of "0xD80F".')
[void]$sb.AppendLine('///')
[void]$sb.AppendLine("/// <para>Generated by <c>scripts/GeneratePrototypeNames.ps1</c> from the $Kind dump file emitted")
[void]$sb.AppendLine('/// by <c>scripts/PrototypeEnumDumper</c>.  Re-run after pulling a fresh dump from a different')
[void]$sb.AppendLine('/// Calligraphy.sip version.  Names are auto-derived from the path basename with CamelCase')
[void]$sb.AppendLine('/// split for readability; for tricky cases edit this file directly or refine the cleanup')
[void]$sb.AppendLine('/// heuristics in the generator.</para>')
[void]$sb.AppendLine('///')
[void]$sb.AppendLine('/// <para>The dictionary is large (thousands of entries) but compiles fast and adds negligible')
[void]$sb.AppendLine('/// startup cost -- the dictionary literal is hoisted into a static field and the hash buckets')
[void]$sb.AppendLine('/// build once on first access.</para>')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine("internal static class $ClassName")
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>Returns the display name for <paramref name="prototypeEnumIndex"/>, or')
[void]$sb.AppendLine('    /// <c>null</c> when the index is unmapped (older Calligraphy version, custom server, or')
[void]$sb.AppendLine('    /// a non-existent prototype id).  Callers should fall back to printing the raw hex id in')
[void]$sb.AppendLine('    /// that case so logs stay searchable.</summary>')
[void]$sb.AppendLine('    public static string? Get(uint prototypeEnumIndex)')
[void]$sb.AppendLine('        => s_names.TryGetValue(prototypeEnumIndex, out var n) ? n : null;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    private static readonly Dictionary<uint, string> s_names = new()')
[void]$sb.AppendLine('    {')

$sorted = $byIndex.Values | Sort-Object Index
foreach ($e in $sorted) {
    $escaped = $e.Name -replace '\\', '\\\\' -replace '"', '\"'
    $line = "        {{ {0,7}u, ""{1}"" }},  // {2}.prototype" -f $e.Index, $escaped, $e.Path
    [void]$sb.AppendLine($line)
}

[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

$dir = Split-Path -Parent $OutputFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
$utf8Bom = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllText($OutputFile, $sb.ToString(), $utf8Bom)

Write-Host ""
Write-Host ("Wrote {0} mappings to {1}" -f $byIndex.Count, $OutputFile)
